"""init

Revision ID: a272036838bb
Revises: e1dfbbf91815
Create Date: 2022-12-14 21:09:22.784024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a272036838bb'
down_revision = 'e1dfbbf91815'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
